apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  template:
    spec:
      containers:
        - name: backend
          image: wafiqhossain/branch_promotion_app:d93020700e5a19499efca0cd3dd77021ee5392d4