apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  template:
    spec:
      containers:
        - name: backend
          image: wafiqhossain/branch_promotion_app:4cef77a1e6b1b127fadcd2a0a2403671e5b6e85a