apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  template:
    spec:
      containers:
        - name: backend
          image: wafiqhossain/branch_promotion_app:147e5d306e941b43366da4116bda30022bffd5af